# Generated by Django 4.2.7 on 2023-11-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categories_text',
            new_name='category_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories_choose',
            new_name='category_choose',
        ),
    ]
